IMAGE_NAME=pm-prepare-meeting-with-customers-image
CONTAINER_NAME=pm-prepare-meeting-with-customers

.PHONY: build run stop

build:
	docker build -t $(IMAGE_NAME) . --no-cache

run:
	docker run --network host --name $(CONTAINER_NAME) -it $(IMAGE_NAME) /bin/bash

stop:
	docker stop $(CONTAINER_NAME)
	docker rm $(CONTAINER_NAME)
