version: '0.1'
services:
  gitlab:
    build:
      context: ./gitlab
    container_name: gitlab
    restart: always
    hostname: '$HOSTNAME'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://$HOSTNAME:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '8929:8929'
      # this port will also used by nextcloud, need to map to another port
      - '8930:443' 
      - '2424:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'