version: '1'

services:
  collabora:
    image: collabora/code:24.04.9.2.1
    container_name: collabora
    restart: always
    ports:
      - "9980:9980"
    environment:
      - extra_params=--o:ssl.enable=false
    extra_hosts:
      - "the-agent-company.com:host-gateway"
    networks:
      - owncloud_network

  owncloud:
    image: owncloud:10.0.10
    container_name: owncloud
    restart: always
    ports:
      - "8091:80"
    environment:
      - OWNCLOUD_DOMAIN=the-agent-company.com:8091
      - OWNCLOUD_TRUSTED_DOMAINS=localhost,the-agent-company.com:8091
      - OWNCLOUD_ADMIN_USERNAME=theagentcompany
      - OWNCLOUD_ADMIN_PASSWORD=theagentcompany
    extra_hosts:
      - "the-agent-company.com:host-gateway"
    volumes:
      - owncloud_data:/var/www/html/data
      - owncloud_config:/var/www/html/config
    networks:
      - owncloud_network

networks:
  owncloud_network:
    driver: bridge

volumes:
  owncloud_data:
  owncloud_config:
