version: '3'

services:
  owncloud:
    image: owncloud:latest
    container_name: owncloud
    restart: always
    ports:
      - "8091:80"
    volumes:
      - owncloud_data:/var/www/html
    environment:
      - OWNCLOUD_DOMAIN=localhost:8091
      - OWNCLOUD_DB_TYPE=sqlite
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin_password
    depends_on:
      - onlyoffice

  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: always
    ports:
      - "8092:80"
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_logs:/var/log/onlyoffice

volumes:
  owncloud_data:
  onlyoffice_data:
  onlyoffice_logs:


  # docker volume rm owncloud_onlyoffice_logs
  # docker volume rm owncloud_onlyoffice_data
  # docker volume rm owncloud_owncloud_data