version: '3'

services:
  collabora:
    image: collabora/code
    container_name: collabora
    restart: always
    ports:
      - "9980:9980"
    environment:
      - extra_params=--o:ssl.enable=false
    networks:
      - owncloud_network

  owncloud:
    image: owncloud:latest
    container_name: owncloud
    restart: always
    ports:
      - "8091:80"
    environment:
      - OWNCLOUD_DOMAIN=localhost:8091
      - OWNCLOUD_TRUSTED_DOMAINS=localhost
      - OWNCLOUD_ADMIN_USERNAME=theagentcompany
      - OWNCLOUD_ADMIN_PASSWORD=theagentcompany
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - owncloud_data:/var/www/html/data
      - owncloud_config:/var/www/html/config
    networks:
      - owncloud_network

networks:
  owncloud_network:
    driver: bridge

volumes:
  owncloud_data:
  owncloud_config: