FROM ghcr.io/theagentcompany/task-base-image:1.0.0

COPY template.md /instruction

# For evaluation purpose only. Make sure the final job description is expected.
COPY requirement.txt /utils 

COPY scenarios.json /npc