version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:17.3.1-ce.0
    container_name: gitlab
    restart: always
    hostname: 'ogma.lti.cs.cmu.edu'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://ogma.lti.cs.cmu.edu:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '8929:8929'
      # this port will also used by nextcloud, need to map to another port
      - '8930:443' 
      - '2424:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'

