# This workflow only validates task images without pushing them to registry
# it acts as a sanity checker without verifying correctness of tasks' contents
name: Validate all task images

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  check-task-structure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install poetry via pipx
      run: pipx install poetry

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'poetry'

    - name: Install Python dependencies using Poetry
      run: poetry install

    - name: Check task structure
      run: |
        bash .github/validate_task_structure.sh

  build-task-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Build base image
      run: |
        cd workspaces/base_image
        make build

    - name: Build task images
      run: |
        for task_dir in workspaces/tasks/*/; do
          echo "Building in $task_dir"
          cd "$task_dir"
          make build
          cd -
        done

  test-evaluator-basic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Build base image
      run: |
        cd workspaces/base_image
        make build

    - name: Run evaluator in each task container
      run: |
        for task_dir in workspaces/tasks/*/; do
          echo "Testing in $task_dir"
          cd "$task_dir"

          docker build -t task-image .

          # Run the container and execute the evaluator
          # The evaluator would almost always say 0 marks granted, but that's
          # fine, we only run it to make sure it at least compiles
          docker run --rm task-image python_default /utils/evaluator.py

          # Capture the exit code
          EXIT_CODE=$?

          # If the evaluator failed, exit the workflow
          if [ $EXIT_CODE -ne 0 ]; then
            echo "Evaluator failed in $task_dir"
            exit $EXIT_CODE
          fi

          cd -
        done